module.exports = {
  apps: [
    {
      name: 'multitenant-backend',
      cwd: '__PROJECT_ROOT__/apps/backend',
      script: 'dist/main.js',
      instances: '__BACKEND_INSTANCES__',
      exec_mode: 'cluster',
      env: {
        NODE_ENV: '__NODE_ENV__',
        PORT: 4000,
      },
      env_file: '__PROJECT_ROOT__/apps/backend/.env',
      max_memory_restart: '1G',
      error_file: '/var/log/multitenant/backend-error.log',
      out_file: '/var/log/multitenant/backend-out.log',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      watch: false,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
    },
    {
      name: 'multitenant-frontend',
      cwd: '__PROJECT_ROOT__/apps/frontend',
      script: 'node_modules/.bin/next',
      args: 'start -p 5000 -H 0.0.0.0',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: '__NODE_ENV__',
        PORT: 5000,
        HOSTNAME: '0.0.0.0',
      },
      max_memory_restart: '512M',
      error_file: '/var/log/multitenant/frontend-error.log',
      out_file: '/var/log/multitenant/frontend-out.log',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      watch: false,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
    },
  ],
};
